### ISSUE TITLE
Singularity Hub Error

### ISSUE THREAD

**Issue by vsoch** [tjhendrickson/BIDS_scripts#1]
Hey just to let you know - you triggered an error in Singularity Hub about a duplicate key value. It looks like the specific container / tag / version (commit) already exists - maybe try deleting the container fully first?

**Comment by vsoch** [comment]
Here is the detail about the commit, etc.

> DETAIL:  Key (name, tag, collection_id, branch, commit)=(tjhendrickson/BIDS_scripts, latest, 1332, master, 86b41094cc4c7cda8a95783aac105f7e0429ff9f) already exists.

I see that in your collection you have one stuck at SETUP - it's probably not going to advance beyond that ;)

**Comment by tjhendrickson** [comment]
Thanks for the message! I was just starting to wonder what the issue was. I ended up just deleting the already built container and re-ran the build. It looks like it is running without issue now.

**Comment by vsoch** [comment]
Awesome! Glad to hear, closing issue.
